server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存
    cache: false
    #开启自定义目录
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: templates/**
mybatis:
  type-aliases-package: com.runke.entity
